SCR_EntityCatalogMultiList {
 m_aMultiLists {
  SCR_EntityCatalogMultiListEntry "{61AE3EB899F53C2F}" {
  }
  SCR_EntityCatalogMultiListEntry "{6A0F6109654AB239}" : "{58E64F0CFD890E6B}Configs/EntityCatalog/US/Weapons/Weapons_Snipers_Reforger.conf" {
   m_aEntities {
    SCR_EntityCatalogInventoryItem "{6685425C46569393}" {
     m_bEnabled 0
    }
   }
  }
  SCR_EntityCatalogMultiListEntry "{6A1007278347DBAF}" {
   m_sIdentifier "Launcher - Panzerfaust 3 (STS)"
   m_aEntities {
    SCR_EntityCatalogInventoryItem "{6A100727D68B4CC0}" {
     m_sEntityPrefab "{5938546A6D2E0381}Prefabs/Weapons/Launchers/Panzerfaust3/Launcher_Panzerfaust3_base.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{6A10072718A08F7F}" {
       m_eItemType ROCKET_LAUNCHER
       m_eItemMode WEAPON
       m_iSupplyCost 150
      }
     }
    }
   }
  }
  SCR_EntityCatalogMultiListEntry "{6A1007273E978E79}" {
   m_sIdentifier "Ammunition - Panzerfaust 3 (STS)"
   m_aEntities {
    SCR_EntityCatalogInventoryItem "{6A1007273294469D}" {
     m_sEntityPrefab "{759BBB84B7704FA0}Prefabs/Weapons/Ammo/Ammo_Rocket_Panzerfaust3.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{6A100727791012A9}" {
       m_eItemType ROCKET_LAUNCHER
       m_eItemMode AMMUNITION
       m_iSupplyCost 0
      }
     }
    }
   }
  }
  SCR_EntityCatalogMultiListEntry "{6A0F610ABCAAF839}" : "{B8CE23CA18F3DA7A}Configs/EntityCatalog/US/Ammunition/Ammo_Snipers_Reforger.conf" {
  }
  SCR_EntityCatalogMultiListEntry "{6A0F610AB9E9E934}" : "{94EE6A9F69705F6E}Configs/EntityCatalog/US/Attachments/Attachments_Grips_WCS.conf" {
  }
  SCR_EntityCatalogMultiListEntry "{6A0F610A94ACA376}" : "{C6C9B0F20E657A2B}Configs/EntityCatalog/US/Attachments/Attachments_Optics_Reforger.conf" {
  }
  SCR_EntityCatalogMultiListEntry "{6A0F610A93787D68}" : "{78478D670AA5C9C2}Configs/EntityCatalog/US/Attachments/Attachments_Other_RHS.conf" {
  }
  SCR_EntityCatalogMultiListEntry "{6A0F610A915AEBB5}" : "{2ADCF83F6E84DA3B}Configs/EntityCatalog/US/Attachments/Attachments_Suppressors_Reforger.conf" {
  }
 }
}