SCR_EntityCatalogMultiList {
 m_aMultiLists {
  SCR_EntityCatalogMultiListEntry "{619028951D30FAC5}" {
   m_aEntities {
    SCR_EntityCatalogInventoryItem "{6A10A6E99102CDE1}" {
     m_sEntityPrefab "{5938546A6D2E0381}Prefabs/Weapons/Launchers/Panzerfaust3/Launcher_Panzerfaust3_base.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{6A10A6E98D58DA54}" {
       m_eItemType ROCKET_LAUNCHER
       m_eItemMode WEAPON
      }
     }
    }
   }
  }
  SCR_EntityCatalogMultiListEntry "{6190289549724388}" {
  }
  SCR_EntityCatalogMultiListEntry "{61902E83F5BCA331}" {
   m_aEntities {
    SCR_EntityCatalogInventoryItem "{6A10A6E92E2BA7D0}" {
     m_sEntityPrefab "{759BBB84B7704FA0}Prefabs/Weapons/Ammo/Ammo_Rocket_Panzerfaust3.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{6A10A6E92D70251B}" {
       m_eItemType ROCKET_LAUNCHER
       m_eItemMode AMMUNITION
      }
     }
    }
   }
  }
  SCR_EntityCatalogMultiListEntry "{61902E829400DABE}" {
  }
  SCR_EntityCatalogMultiListEntry "{61904044C7311E2A}" {
  }
  SCR_EntityCatalogMultiListEntry "{61B68723B01F077A}" {
  }
  SCR_EntityCatalogMultiListEntry "{61AE3EB899F53C2F}" {
  }
  SCR_EntityCatalogMultiListEntry "{C99C0105CCCDF4DE}" {
  }
  SCR_EntityCatalogMultiListEntry "{6A10A6ECB4CB98CD}" : "{7F400FAAA7810DBD}Configs/PBK_ArsenalList_Configs/PBK_Attachments.conf" {
  }
  SCR_EntityCatalogMultiListEntry "{6A10A6EC23F7BE2D}" : "{1411AB75C673977C}Configs/PBK_ArsenalList_Configs/PBK_Backpacks.conf" {
  }
  SCR_EntityCatalogMultiListEntry "{6A10A6EC20AEB919}" : "{B5EDEB9F45C7DB3B}Configs/PBK_ArsenalList_Configs/PBK_Belts.conf" {
  }
  SCR_EntityCatalogMultiListEntry "{6A10A6EC10902753}" : "{F9C7DABF65186458}Configs/PBK_ArsenalList_Configs/PBK_BodyArmour.conf" {
  }
  SCR_EntityCatalogMultiListEntry "{6A10A6EC110A6BA2}" : "{4EC00C7E2527252C}Configs/PBK_ArsenalList_Configs/PBK_Clothing.conf" {
  }
  SCR_EntityCatalogMultiListEntry "{6A10A6EC101EF022}" : "{7E001E0E511853F4}Configs/PBK_ArsenalList_Configs/PBK_ClothingBits.conf" {
  }
  SCR_EntityCatalogMultiListEntry "{6A10A6EC1309B3C4}" : "{39550932B57F4D08}Configs/PBK_ArsenalList_Configs/PBK_EyeWear.conf" {
  }
  SCR_EntityCatalogMultiListEntry "{6A10A6EC13989B86}" : "{24A84CE1ECA9637F}Configs/PBK_ArsenalList_Configs/PBK_FootWear.conf" {
  }
  SCR_EntityCatalogMultiListEntry "{6A10A6EC5947951D}" : "{0684611A3C2379CC}Configs/PBK_ArsenalList_Configs/PBK_Gloves.conf" {
   m_aEntities {
    SCR_EntityCatalogEntry "{691134502D4CE541}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogEntry "{6911345028073152}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogEntry "{691134502A4E2F85}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogEntry "{69113450249B4C93}" {
     m_bEnabled 0
    }
   }
  }
  SCR_EntityCatalogMultiListEntry "{6A10A6EC54724835}" : "{B8C1C183B9BA0F8A}Configs/PBK_ArsenalList_Configs/PBK_Hats.conf" {
  }
  SCR_EntityCatalogMultiListEntry "{6A10A6EC57EF60D8}" : "{63C8DB83486DC02F}Configs/PBK_ArsenalList_Configs/PBK_Headsets.conf" {
  }
  SCR_EntityCatalogMultiListEntry "{6A10A6EC577CDACC}" : "{977874626621E3BE}Configs/PBK_ArsenalList_Configs/PBK_Helmets.conf" {
  }
  SCR_EntityCatalogMultiListEntry "{6A10A6EC5681DB6C}" : "{F03CD8237F8E4DB6}Configs/PBK_ArsenalList_Configs/PBK_Masks.conf" {
  }
  SCR_EntityCatalogMultiListEntry "{6A10A6EC5609B93B}" : "{B0FB6998D3490D78}Configs/PBK_ArsenalList_Configs/PBK_Patches.conf" {
  }
  SCR_EntityCatalogMultiListEntry "{6A10A6EC5981A74C}" : "{686B4BD06260AF29}Configs/PBK_ArsenalList_Configs/PBK_Throwables.conf" {
  }
  SCR_EntityCatalogMultiListEntry "{6A10A6EFDDAAAC3E}" : "{9A82FCF5FB0B207A}Configs/PBK_ArsenalList_Configs/PBK_Webbing.conf" {
  }
 }
}