SCR_EntityCatalogMultiListEntry {
 m_aEntities {
  SCR_EntityCatalogInventoryItem "{660329CED2D5B75F}" {
   m_aEntityDataList {
    SCR_ArsenalItem "{64F92170B37D891B}" {
     m_eRequiredRank CAPTAIN
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{660329CEDA30B551}" {
   m_bEnabled 0
  }
 }
}