SCR_EntityCatalogMultiList {
 m_aMultiLists {
  SCR_EntityCatalogMultiListEntry "{64CF5EF555AF4A51}" {
   m_aEntities {
    SCR_EntityCatalogInventoryItem "{617E8CEAD552163B}" {
     m_bEnabled 0
    }
   }
  }
  SCR_EntityCatalogMultiListEntry "{66C2F14062E412D4}" {
   m_aEntities {
    SCR_EntityCatalogInventoryItem "{6556A2FFC51E2722}" {
     m_bEnabled 0
    }
   }
  }
 }
}