SCR_EntityCatalogMultiList {
 m_aMultiLists {
  SCR_EntityCatalogMultiListEntry "{64485E226638CB8E}" {
   m_aEntities {
    SCR_EntityCatalogInventoryItem "{5DD538CFFF2D7A5C}" {
     m_bEnabled 0
    }
   }
  }
  SCR_EntityCatalogMultiListEntry "{64485E232553D7AE}" {
   m_aEntities {
    SCR_EntityCatalogInventoryItem "{5DB2BC15617E7409}" {
     m_bEnabled 0
    }
   }
  }
 }
}