SCR_EntityCatalogMultiList {
 m_aMultiLists {
  SCR_EntityCatalogMultiListEntry "{644872C86FB5983B}" {
   m_aEntities {
    SCR_EntityCatalogInventoryItem "{61B23E8E0ED811E0}" {
     m_bEnabled 0
    }
   }
  }
  SCR_EntityCatalogMultiListEntry "{644872C86F45BE78}" {
   m_aEntities {
    SCR_EntityCatalogInventoryItem "{646D3AE3F00B31DB}" {
     m_bEnabled 0
    }
   }
  }
  SCR_EntityCatalogMultiListEntry "{644872C860FA24CC}" {
   m_aEntities {
    SCR_EntityCatalogInventoryItem "{5D4A87EB9A03E210}" {
     m_bEnabled 0
    }
   }
  }
  SCR_EntityCatalogMultiListEntry "{64485E22667C69B7}" {
   m_aEntities {
    SCR_EntityCatalogInventoryItem "{69DD2A5BF1F3B823}" {
     m_bEnabled 0
    }
   }
  }
  SCR_EntityCatalogMultiListEntry "{64485E226638CB8E}" {
   m_aEntities {
    SCR_EntityCatalogInventoryItem "{5D4A87EB99D38463}" {
     m_bEnabled 0
    }
   }
  }
  SCR_EntityCatalogMultiListEntry "{64485E2266018F38}" {
   m_aEntities {
    SCR_EntityCatalogInventoryItem "{64D6276F915BAF64}" {
    }
   }
  }
  SCR_EntityCatalogMultiListEntry "{64485E2266A19667}" {
   m_aEntities {
    SCR_EntityCatalogInventoryItem "{660511B9CB0819CD}" {
    }
   }
  }
  SCR_EntityCatalogMultiListEntry "{64485E22310F973C}" {
   m_aEntities {
    SCR_EntityCatalogInventoryItem "{69DD2A5A2F2767ED}" {
     m_bEnabled 0
    }
   }
  }
  SCR_EntityCatalogMultiListEntry "{64CF5EF555AF4A51}" {
   m_aEntities {
    SCR_EntityCatalogInventoryItem "{617E8CEAD552163B}" {
     m_bEnabled 0
    }
   }
  }
  SCR_EntityCatalogMultiListEntry "{66C2F14062E412D4}" {
   m_aEntities {
    SCR_EntityCatalogInventoryItem "{6556A2FFC51E2722}" {
     m_bEnabled 0
    }
   }
  }
 }
}