SCR_Faction : "{E7B7EA4823DD81F0}Configs/Factions/BLUFOR.conf" {
 m_aEntityCatalogs {
  SCR_EntityCatalogMultiList "{5C9E82F29B327997}" : "{D83A5EFEEF6CBF61}Configs/EntityCatalog/US/Vehicles_EntityCatalog_US.conf" {
  }
  SCR_EntityCatalogMultiList "{5C68A0EEB3F124F9}" : "{79A8A3BB246D0829}Configs/EntityCatalog/US/STS_InventoryItems_EntityCatalog_US.conf" {
  }
 }
}