SCR_MissionHeaderCampaign {
 World "{F4E2A1BF76B76795}Worlds/STS_Zarichne_Conflict_AAS_Layout1.ent"
 SystemsConfig "{7C9E720397CC6ACD}Configs/Systems/ConflictSystems.conf"
 m_sName "[STS]_WCS_Zarichne - AAS #1"
 m_sAuthor "OG: FAL & WCS - edited by the STS"
 m_sPath "{F4E2A1BF76B76795}Worlds/STS_Zarichne_Conflict_AAS_Layout1.ent"
 m_sDescription "#AR-Campaign_GamemodeDesc"
 m_sDetails "#AR-Campaign_Hint_Signal_Text"
 m_sIcon "{71BB3843C2BA3DE7}Assets/UI/zariche_sts_aas.edds"
 m_sLoadingScreen "{71BB3843C2BA3DE7}Assets/UI/zariche_sts_aas.edds"
 m_sPreviewImage "{42F29552F4A0BE72}UI/Textures/MissionLoadingScreens/WCS_Zarichne.edds"
 m_sGameMode "#AR-Campaign_GamemodeName"
 m_iPlayerCount 64
 m_eEditableGameFlags SpawnVehicles
 m_eDefaultGameFlags SpawnVehicles
 m_fDayTimeAcceleration 2.4
 m_fNightTimeAcceleration 2.4
 m_bRandomStartingWeather 1
 m_bRandomWeatherChanges 1
 m_bMapMarkerEnableDeleteByAnyone 1
 m_WCS_Core_Settings WCS_Core_Settings "{6A0D4350B7932440}" {
 }
 m_WCS_LoadoutEditor_Settings WCS_LoadoutEditor_Settings "{6A10A6ED3E88CE05}" {
 }
 m_WCS_VON_Settings WCS_VON_Settings "{6A10A6EDCC1664E4}" {
  m_bAlwaysShowEnemyNames 0
 }
 m_WCS_SpawnProtection_Settings WCS_SpawnProtection_Settings "{6A10A6EDE9F90AB6}" {
  m_bEnableKillZone 1
  m_bEnableWarningZone 1
  m_bEnableMasterArmZone 1
  m_fKillZoneRespawnPenalty 30
 }
}